# Generated by Django 4.2.2 on 2025-02-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="instagram_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Instagram ID"
            ),
        ),
    ]
