# Generated by Django 4.2.2 on 2025-03-08 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_menu", "0002_settings_instagram_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("address", models.TextField(verbose_name="آدرس")),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.RemoveField(
            model_name="settings",
            name="address",
        ),
        migrations.RemoveField(
            model_name="settings",
            name="call_number",
        ),
        migrations.CreateModel(
            name="BranchCallNumbers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_number",
                    models.CharField(max_length=100, verbose_name="شماره تماس"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_numbers",
                        to="app_menu.branches",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch Call Number",
                "verbose_name_plural": "Branch Call Numbers",
            },
        ),
    ]
