# Generated by Django 4.2.2 on 2025-03-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_menu", "0003_branches_remove_settings_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branchcallnumbers",
            options={
                "verbose_name": "شماره تماس شعبه",
                "verbose_name_plural": "شماره تماس شعبات",
            },
        ),
        migrations.AlterModelOptions(
            name="branches",
            options={"verbose_name": "شعبه", "verbose_name_plural": "شعبات"},
        ),
        migrations.AddField(
            model_name="settings",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="توضیحات کوتاه"
            ),
        ),
        migrations.AlterField(
            model_name="branchcallnumbers",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branch_numbers",
                to="app_menu.branches",
                verbose_name="شعبه",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="instagram_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="آیدی اینستاگرام"
            ),
        ),
    ]
